### ISSUE TITLE
"Untitled" seems to be hard-coded in English

### ISSUE THREAD

**Issue by mudrd8mz** [academic-moodle-cooperation/moodle-local_downloadcenter#1]
The unnamed sections seem to be named like "Untitled" which is hard-coded in English in the code, unable to be localized.

**Comment by moniNaydenov** [comment]
Hi David,

Thanks for pointing that out!
The main consideration for this was to avoid having non-latin names in the filename. Do you think it is safe to include it as a language string?

**Comment by mudrd8mz** [comment]
If you use the Moodle core's `zip_archive` class to prepare the ZIP, there should be an in-built support for cleaning up the file names.

**Comment by moniNaydenov** [comment]
Yes, we use the zip_packer class, which in turn uses zip_archive. Great then, I'll add the language string for the next release.

**Comment by kaspot** [comment]
I‘ve also added right now an issue in our bugtracking system, so that it will be implemented within the next release.

**Comment by moniNaydenov** [comment]
Issue solved - branch master and MOODLE_33_STABLE
Thanks again for pointing that out!
