### ISSUE TITLE
Handling of large archives

### ISSUE THREAD

**Issue by claell** [academic-moodle-cooperation/moodle-local_downloadcenter#10]
I got aware of this because of #2.

It seems like currently the archive is first generated on the server and then delivered to the user. That unfortunately can result in long waiting times until the download is finally available and might even cause timeouts. Both is pretty inconvenient for the users.

I know from cloud hosting providers like Google Drive that there is a different way to deliver a zip archive. They probably generate it while the file is already downloaded. That way there is no wait time for the archive generation.

One downside is that there is no size displayed for the downloaded file. Another one might be that the archive cannot be compressed, but I am not sure about that point.

A benefit might be that there is no disk usage on server side for generating the archive (but also not sure about this point).

**Comment by moniNaydenov** [comment]
Thank you for your comment! We will research how compressing and downloading of large files is handled in other places (Google Drive), and we will get back to you.

**Comment by lorenzulrich** [comment]
In my experience, creating such large files synchronously is not a very good option. Of course you can always raise limits, but you must ask yourself if it's really wise to have timeouts > 300 seconds for large archives. An elegant solution would be to have a job queue (such as beanstalkd) that asynchronously generates the file. The browser is only and repeatedly pinging if the job is complete and starts the download as soon as it is complete.
However, such queue implementations are creating new dependencies to services that may not be available for all hostings.

**Comment by claell** [comment]
@lorenzulrich it seems you are rather commenting on #2 instead of this issue, at least when you are talking about better solutions than timeouts.

Are you referring to my suggestion with "creating such large files synchronously"? Can you elaborate why this is not a good option? Many Cloud providers use this.

**Comment by lorenzulrich** [comment]
@claell Sorry, it seems I didn't properly read all the comments. What I meant is that "generating the files synchronously before delivering them" might not be a good idea. I don't have experience with "while delivering them", so I suggested a third way (asynchronous generation). But if Google etc. generate ZIP files synchronously during the download, that would certainly be a good solution. Sorry for the confusion.

**Comment by claell** [comment]
Alright. I agree to you that the current timeout solution is rather bad. So let's hope a better solution gets implemented, soon.

Also ping @t-schroeder, maybe you are interested in looking into such solutions.

**Comment by goggo24** [comment]
with v.3.11.1 we changed the download to a stream zip
