### ISSUE TITLE
assuming that mod_book is installed

### ISSUE THREAD

**Issue by ndunand** [academic-moodle-cooperation/moodle-local_downloadcenter#13]
In https://github.com/academic-moodle-cooperation/moodle-local_downloadcenter/blob/master/locallib.php#L174 this plugin assumes without checking that mod_book is installed. Even though mod_book is part of the standard Moodle distribution, it could have been uninstalled.

One option would be to make this explicit by using `$plugin->dependencies` in `version.php`. Another option would be to move this `require_once` to the code actually dealing with a mod_book resource, i.e. around lines 381+ of the same file.

**Comment by goggo24** [comment]
Thanks for your feedback.  I'm not sure, if we even check if the other supported plugins are installed. We will have a look,

**Comment by goggo24** [comment]
included in v.3,9.0 - coming soon!
