### ISSUE TITLE
One folder per file

### ISSUE THREAD

**Issue by lorenzulrich** [academic-moodle-cooperation/moodle-local_downloadcenter#14]
For most files, the download center generates a sub folder per file with the same name as the file.

Example:

![image](https://user-images.githubusercontent.com/1816023/68576777-ffa2e280-046e-11ea-8653-83e7b65fe3bb.png)

I would expect that this file would be placed inside the folder `VA 1 Einführung, 10.09.2018`. However, it is placed in `VA 1 Einführung, 10.09.2018\VA1 H18 Praes`:

![image](https://user-images.githubusercontent.com/1816023/68576816-1d704780-046f-11ea-8e2a-9064ff8336f3.png)

Is this an intentional behaviour?

**Comment by goggo24** [comment]
Yes it is ;) 
We have thought a long time about how we can best present the course structure in the ZIP. Everything is clear, if the title is the same as the file name behind or let's say nearly similar. But it's possible in Moodle (and it's common) that the title is different from the filename. Tests with users have shown us, that when only the file is downloaded, they could not make the connection with the course structure. 
So we implemented it the way: folder name=activity name  &  folder content=original file name
Do you have any suggestions, how we can improve it?

**Comment by nickvarney** [comment]
Whilst understanding the potential file name disparity between a display name and the actual file name, it's difficult to think of a use case for receiving every file resource in its own folder. Receiving them this way makes it difficult to work with these files locally. What would be great would be to provide the _option_ to receive the files directly inside the section/topic folder for those that want to view and work with the original files in bulk.

**Comment by goggo24** [comment]
Thanks for your suggestion. So only the first level topic/section should be a folder - right?

**Comment by nickvarney** [comment]
> Thanks for your suggestion. So only the first level topic/section should be a folder - right?

Yes, that's correct.

Whilst maintaining the current behaviour for folder resources within a topic i.e. show them as a sub-folder within a topic, with the individual files contained within it.

**Comment by nickvarney** [comment]
> Thanks for your suggestion. So only the first level topic/section should be a folder - right?

Could I gently ask if this request is being considered? Thanks.

**Comment by goggo24** [comment]
After our internal discussion, we added it to the backlog - we will implement it probably for 4.3. or 4.4. The folder for topics will remain, but the the subfolders should be reduced.

**Comment by nickvarney** [comment]
> After our internal discussion, we added it to the backlog - we will implement it probably for 4.3. or 4.4. The folder for topics will remain, but the the subfolders should be reduced.

Thank you so much!

**Comment by goggo24** [comment]
Good news, we are already working on it and It will be included in v.4.3.0 - subfolder will only be added, if useful (e.g. assignment). Folder for topics will remain.  Furthermore, there will be a new option to add numbering, so that the order of elements remains unchanged.

**Comment by mwreichel** [comment]
Hi, as already mentioned, the feature will be included in our next major release, which will be published soon.
