### ISSUE TITLE
File extensions are incorrect for some files

### ISSUE THREAD

**Issue by roessling** [academic-moodle-cooperation/moodle-local_downloadcenter#16]
Hi,
since (I assume) Moodle 3.8, some files end up with an incorrect extension:

- ZIP files in a course end up as "<filename>.zip**.h5p**

- Racket files end up as "<filename>.rkt**.txt** (Racket / .rkt) is a file for an editor for a functional programming language we use in our teaching)
Both "added extensions" are unfortunate, as they interfere with other processes and the normal use of the tools.

**Comment by goggo24** [comment]
Thanks for reporting. We are already working on fixing the error.

**Comment by mkemmerling** [comment]
Fixed in version 3.8.1. Thanks again for reporting.
