### ISSUE TITLE
Left Margin on .path-local-downloadcenter .mform .row.downloadcenter_selector CSS

### ISSUE THREAD

**Issue by felicemcc** [academic-moodle-cooperation/moodle-local_downloadcenter#18]
Hello! 
We installed the Download Center which fits our needs, but when we enter that section on any course, we get some text cut out (see the attached file - below the warning).

Would you mind adding the following line to this CSS class?

```
.path-local-downloadcenter .mform .row.downloadcenter_selector {
    margin-top: 0;
    margin-bottom: 0;
    **margin-left: 0;**
}
```

Best regards! 

![Screenshot from 2020-01-14 17-38-18](https://user-images.githubusercontent.com/6146673/72363921-f4ca2f80-36f5-11ea-99f4-acba645c8afe.png)

**Comment by goggo24** [comment]
We don't have this behaviour in our instances. I just tried it with classic theme and it looked also nice. Which version of downloadcenter / moodle core and which theme do you use?

**Comment by goggo24** [comment]
could not be reproduced => close
