### ISSUE TITLE
execution time issue when zipping very large course

### ISSUE THREAD

**Issue by CamilleTrd** [academic-moodle-cooperation/moodle-local_downloadcenter#2]
Hi, 

I had an issue for creating and downloading a very large course on **Moodle 3.5**. The process was stopping and giving me a white page with no error log. 

But by adding in the **set_time_limit()** to 300s (5mn) (--> http://www.php.net/set_time_limit) at the begining of the function` locallib.php > create_zip()` line 164 just after the global declaration, it solved the issue.

5mn might be exaggerated but 2-3mn could be a good idea.

NB: My downloaded folder was 1.7GB.

Best,
Cam

**Comment by goggo24** [comment]
Hey Cam, sorry for the late reply. First, thanks for reporting. Second, we will have a look and afterwards report back our solution/decision. Bye, Eva.

**Comment by goggo24** [comment]
Fix included in v.3.6.1 - coming soon!
