### ISSUE TITLE
Downloaded ZIP file is damaged

### ISSUE THREAD

**Issue by tdeamos** [academic-moodle-cooperation/moodle-local_downloadcenter#21]
Hello everybody.

When I try to download files from a large course, ZIP file is generated and downloaded, but when I try to open it, a message says: "The archive is either in unnown format or damaged."

I also tried to select a few files from the mentioned course, but it continues failing.

My Moodle version is 3.7 and am using v3.7.0 of the plugin.
PHP Version 7.2.31-1
Ubuntu18.04.1

Regards.

Tomas.

![image](https://user-images.githubusercontent.com/1648524/87584364-c1238e80-c6b3-11ea-854e-e0c5a25e62e7.png)

**Comment by tdeamos** [comment]
Hi everybody.
Excuse me for my insistence. Did you see this error message before? Any clues on what might be causing the issue?
Thanks and regards.
Tomas.

**Comment by tdeamos** [comment]
Hi everybody.
Looked at Apache error logs but coundn´t fin any relevant information. Any clues on what might be causing the issue?
Thanks and regards.
Tomas.

**Comment by tdeamos** [comment]
Hi everybody.
Any clues on what might be causing this issue? If anybody could give me a hint on where to look I would really appreciete it.
It´s a pity, but if we get no support, we are going to remove this plugin from our environment.
Thanks and regards.
Tomas.

**Comment by goggo24** [comment]
Maybe the special characters in the name? Are you still on 3.7?

**Comment by tdeamos** [comment]
Thanks Eva.
Finally upgraded to Moodle 3.9 and problem seems to be solved.
Regards.
Tomas.
