### ISSUE TITLE
Compatibility with Adaptable theme

### ISSUE THREAD

**Issue by dcombes** [academic-moodle-cooperation/moodle-local_downloadcenter#22]
I have just installed the plugin but can't seem to locate the Download Centre link on a course page. I see from the documentation that it resides in the Navigation Block, but because we're on Moodle 3.7 and use an Adaptable theme we have a NavBar instead of a Block. Does anyone know if this plugin is compatible? And if so, how I can make it appear?

All the best
David

**Comment by BBberghman** [comment]
I have the same question, any updates?

**Comment by goggo24** [comment]
Sorry for coming back so late. We don't have any experience with adaptapble theme. The plugins appears within the navigation block or with standard theme boost in the left navigation area (under participants).

**Comment by goggo24** [comment]
Since we use moodle standard interfaces for display, we will close this issue. Maybe a request to the maintainer of adaptable theme can help. Of course, the direct link can also be be integrated elsewhere - call via _..../local/downloadcenter/index.php?courseid=xxxx_
