### ISSUE TITLE
Doesn't display the ampersand corectly

### ISSUE THREAD

**Issue by argwallace** [academic-moodle-cooperation/moodle-local_downloadcenter#23]
For those topics that contain an "&" ampersand in their name, it doesn't display correctly but rather "amp;" instead. Any way to correct this? Thanks!

Stephen

**Comment by goggo24** [comment]
Thanks for reporting - we will have a look what we can do.

**Comment by goggo24** [comment]
Fixed.

**Comment by argwallace** [comment]
> Fixed.

Hey! Great! I am still on 3.8.x and see the fix for this is for 3.10. Is this version compatible with 3.8? If not, will the fix be included for any previous versions?

thanks.
