### ISSUE TITLE
Feedback on Warning Test

### ISSUE THREAD

**Issue by michaelwayneharris87** [academic-moodle-cooperation/moodle-local_downloadcenter#24]
I received feedback from our Moodle administrator that they were confused by the wording of the text provided in the `$string['warningmessage']` variable (from the `lang/en/local_downloadcenter.php` file). Ideally, they would like the ability to customize the text through the GUI. Alternatively, they suggested something like "Note: Download Center does not show hidden files or folders." or "NOTE: DOWNLOAD CENTER only enables you to download visible files and folders."

We are running version 2019111501, but it looks like the string is hard coded in the file in the most recent version.

**Comment by goggo24** [comment]
The string shouldn't be hardcoded - if you want to change it, you can do a local customisation. We will adjust the sentence in the next version. Thanks for the feedback. We changed the german one, but forgot about the english.

**Comment by goggo24** [comment]
@michaelwayneharris87 We will change it to => NOTE: Download center only enables you to download visible FILES and FOLDERS! 
Does this work?

**Comment by michaelwayneharris87** [comment]
Sounds great. Thank you!

**Comment by goggo24** [comment]
The change is included in v.3.11 - coming this weekend ;)
