### ISSUE TITLE
Folders/Files with non Windows compatible characters

### ISSUE THREAD

**Issue by Syxton** [academic-moodle-cooperation/moodle-local_downloadcenter#26]
If you download a section that has a ? (or other characters that Windows doesn't allow) the zip file will download but will show empty if using default Microsoft Explorer to open the .zip file.  If you use another program, like 7zip you can still extract the files from the .zip.

**Comment by Syxton** [comment]
Related to https://tracker.moodle.org/browse/MDL-36961

**Comment by goggo24** [comment]
I just tried it with a section "Files ?" with v.3.11.1 => the folder name gets "Files _" and with default Windows Explorer i can open it without problems. Which version of our plugin do you use? Does the erros still occurs with a newer version?

**Comment by Syxton** [comment]
@goggo24 We are using download center version: 2021051801 with Moodle 3.11.  This does not seem to be an issue for us anymore.

**Comment by goggo24** [comment]
@Syxton thanks for the fast feedback, than i will close the issue.
