### ISSUE TITLE
Clicking Select "None" does not disable the activities/resources

### ISSUE THREAD

**Issue by kiratskitizing** [academic-moodle-cooperation/moodle-local_downloadcenter#3]
The Select / None link unticks all the section heading and activities. However, it does not disable the check boxes, which allows a user to tick activities/resources (without ticking the section heading) and download them. The result of this is an empty zip file.

Steps to replicate:
1. Create a course.
2. Turn editing on.
3. On Section 1, add the following:
a. Resource / File
Name: Word doc 1
Select files: Upload a word doc
b. Resource / File
Name: PDF 1
Select files: Upload a pdf file.
4. On Section 2, add the following:
a. Resource / File
Name: Word doc 2
Select files: Upload a word doc
b. Resource / File
Name: PDF 2
Select files: Upload a pdf file.
5. Click "Download center" on the navigation block.
6. Click the "Select None" link to untick all boxes.
Make sure topic 1 (section heading) is unticked.
Tick Word Doc 1
Tick PDF 1
Make sure topic 2 (section heading) is unticked.
Tick Word Doc 2
Tick PDF 2
Click the "Create ZIP archive" button.
Result: You well be able to download a zip file which contains nothing.

**Comment by goggo24** [comment]
Thanks for reporting and for providing a pull request. We will take a look.

**Comment by goggo24** [comment]
included in v.3.6.0 - coming soon!
