### ISSUE TITLE
In course format flexsections only the first 4 sections are downloaded

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-local_downloadcenter#30]
The course format flexsections sets the format option "numsections" to 4. It doesn't get changed if you add more sections after creating the course. So the downloadcenter will only show and download course content from the first 4 sections in courses that use the flexsections format.

I'm not sure whether that should be fixed in the downloadcenter or in the flexsections plugin.

**Edit:** This doesn't seem to be a problem caused by the flexsections course format. In our case it just affected only courses using the flexsections format. I haven't been able to reproduce how our users managed to create courses using the format flexsections and the format option "numsections".

**Comment by t-schroeder** [comment]
This is the part of the code I'm talking about: https://github.com/academic-moodle-cooperation/moodle-local_downloadcenter/blob/0d71726d3005e3212306867d2fda70df701fffd0/locallib.php#L98-L105

**Comment by marinaglancy** [comment]
'numsections' is an optional property of a course format that is not used in the format_flexsections. It may be present in the database if the course was converted from another format that used 'numsections'.  The better way to retrieve the 'numsections' that will return a value only if the format has this property:

    $numsections = course_get_format($course)->get_format_options()['numsections'] ?? null

**Comment by goggo24** [comment]
Thanks, we will have a look and  plan to include it for 4.3.

**Comment by mwreichel** [comment]
Hi, as already mentioned, the fix will be included in our next major release - 4.3. It will be published soon.
