### ISSUE TITLE
Assignment setting "Only show files during submission" not respected

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-local_downloadcenter#31]
Students can download additional files for assignments that haven't started yet, regardless of whether the option "Only show files during submission" is selected in the assignment's settings.

That should not be possible. The files should probably only be downloadable when students can actually see them. That usually means when the "Allow submissions from" time has passed and the "Cut-off date" hasn't. But the files could be visible for longer, e.g. if the student got granted an extension or if the assignment has a group/user override that applies.

This is the setting in the assignment activity that I'm talking about:

![image](https://github.com/academic-moodle-cooperation/moodle-local_downloadcenter/assets/24255259/8019559f-bbdc-4e0e-a403-94bc7a53c233)

**Comment by mwreichel** [comment]
Hi @t-schroeder,
thank you for reporting this.
You're totally right, this should not be possible. We'll fix this.

Kind regards,
Martin

**Comment by mwreichel** [comment]
Fixed with version 4.4.1
