### ISSUE TITLE
Exclude empty topics

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-local_downloadcenter#5]
We would like for all empty topics to be excluded from the downloaded zip. There should probably also be some indication on index.php that the empty folders will not be exported, e.g. they could just not be displayed there.

We're going to fork this plugin and make these changes anyway. I was just wondering if you'd be ok with merging them back into the main repo later? Should we add a setting (for admins) with which you can toggle this behavior on or off?

**Comment by goggo24** [comment]
We would appreciate to merge it back to our repository. Please provide a setting for admins to controll this behavior (default no = empty folders will be exported).  In two weeks moodle_36_stable will propably be released for this plugin. Looking forward to your pull request. Thanks.

**Comment by claell** [comment]
@t-schroeder Any update on this?

**Comment by goggo24** [comment]
@t-schroeder will there be a pull request from your side?

**Comment by t-schroeder** [comment]
@claell @goggo24 Yes. Thanks for reminding me. We will submit a pull request within the next couple of days.

**Comment by ndunand** [comment]
@t-schroeder we'd be glad to have this feature too
also, I could peer review your code (if wanted) or help with the implementation

**Comment by ndunand** [comment]
Sorry @t-schroeder just saw your PR. Waiting on @goggo24 to accept/merge...

**Comment by goggo24** [comment]
Included in v.3.9.0. - adminsetting to exclude empty topics (default: no) - coming in the next days!
