### ISSUE TITLE
Navigation placement conflicts with other plugin

### ISSUE THREAD

**Issue by t-schroeder** [academic-moodle-cooperation/moodle-local_downloadcenter#6]
We're planning to use this plugin together with https://moodle.org/plugins/local_boostnavigation with the extra collapsible "Sections" node enabled. This is how it looks:

![sections-collapsed](https://user-images.githubusercontent.com/24255259/48947100-4c28a180-ef30-11e8-8310-d4bce61aeee6.PNG)

![sections-expanded](https://user-images.githubusercontent.com/24255259/48947103-4e8afb80-ef30-11e8-9764-fd5b0b9e2fd8.PNG)

Notice how the Download center is placed after the Sections node, but before the actual sections. This is because both plugins insert a node before the first section. But local_boostnavigation does it before the local_downloadcenter because the "extend_navigation" callbacks of the local plugins are called in alphabetical order of the plugin names. That's why the downloadcenter adds its node last. If the downloadcenter node would be added first, I assume there wouldn't be a problem.

But since the plugin names are what they are I'm reporting this for this plugin instead of for local_boostnavigation because I think it would be cleaner to handle this problem in the downloadcenter. Would you be willing to change the downloadcenter by adding compatibility with other third-party plugins?

As I stated in the previous issue we would implement this anyway for our Moodle setup. I was just wondering if this belongs here.

P.S.: This could probably also be solved in local_boostnavigation by changing the type of their custom "Section" node from `TYPE_CUSTOM` to `TYPE_SECTION` but I can't tell what side effects that would have, not to mention the types probably shouldn't be used that way.

**Comment by goggo24** [comment]
Could you please tell me the which version of the downloadcenter you use? We already fixed the bug (v.3.5.+), because we also use the local_boostnavigation :)

<img width="375" alt="downlaod_section" src="https://user-images.githubusercontent.com/16721900/48952357-3623dc80-ef42-11e8-82d5-47abe8774938.png">

**Comment by t-schroeder** [comment]
We're currently using the version from the Moodle Plugin repository for Moodle 3.5. Glad to hear this has already been fixed. :+1:

**Comment by goggo24** [comment]
included in v3.5.0 (2018050800) 
https://moodle.org/plugins/pluginversions.php?plugin=local_downloadcenter
