### ISSUE TITLE
Deselecting the top item makes children not selectable

### ISSUE THREAD

**Issue by claell** [academic-moodle-cooperation/moodle-local_downloadcenter#9]
When deselecting an item that is on a higher level in hierarchy the checkboxes for the child items are currently greyed out leaving them not selectable.

This behaviour is uncommon, I'd expect that deselecting the top item will also unselect all child checkboxes and after that one can select those child items that are wanted. Maybe the behaviour can be adjusted accordingly.

Let me know if you need more details or screenshots.

**Comment by goggo24** [comment]
I can follow your explanation and understand why you wanna change it ;)
At the moment the clicking is working like in the "import" moodle-core function of a course. I will take this change and discuss it within the AMC and let you know what we decided.

**Comment by claell** [comment]
Ah, I do not know the import function. Is it reasonable to have it like this in the import function? Or might it be good to change it there as well? Then both functions would behave coherent.

**Comment by goggo24** [comment]
Improvements with selecting/deselecting topics and items included in v.3.9.0.
